import { logger } from "../observability/logger";
import { metrics } from "../observability/metrics";
import { liquidityPool } from "./liquidity-pool";

export interface RebalanceEvent {
  id: string;
  timestamp: string;
  sourcePool: string;
  targetPool: string;
  amount: number;
  reason: string;
}

class AutoRebalanceService {
  private history: RebalanceEvent[] = [];
  private lastRebalance: number = Date.now();

  /**
   * Periodically checks registry health and reserve drift to decide if a rebalance is needed.
   */
  async checkAndRebalance(): Promise<RebalanceEvent | null> {
    const poolMetrics = await liquidityPool.getMetrics();
    
    // Heuristic: If reserve ratio is below 35%, trigger an autonomous infusion from the surplus enclave
    if (poolMetrics.reserveRatio < 0.35) {
      return this.executeRebalance("SURPLUS_ENCLAVE", "MAIN_RESERVE", 250000, "RESERVE_DRIFT_CRITICAL");
    }

    // Heuristic: If TVL is exceptionally high but APY is lagging, optimize yield deployment
    if (poolMetrics.totalValueLocked > 5000000 && poolMetrics.currentAPY < 10) {
      return this.executeRebalance("MAIN_RESERVE", "YIELD_OPTIMIZER_V1", 100000, "YIELD_EFFICIENCY_BOOST");
    }

    return null;
  }

  private async executeRebalance(source: string, target: string, amount: number, reason: string): Promise<RebalanceEvent> {
    const event: RebalanceEvent = {
      id: `reb_${Math.random().toString(36).substring(7)}`,
      timestamp: new Date().toISOString(),
      sourcePool: source,
      targetPool: target,
      amount,
      reason
    };

    this.history.unshift(event);
    this.lastRebalance = Date.now();
    
    logger.info('Finance', `AUTONOMOUS REBALANCE: Shifting ${amount} GC from ${source} to ${target} [${reason}]`);
    metrics.track('liquidity_rebalance', amount, { source, target, reason });

    return event;
  }

  async getHistory(): Promise<RebalanceEvent[]> {
    return this.history.slice(0, 10);
  }

  async getEfficiencyBoost(): Promise<number> {
    // Simulated yield boost generated by rebalancing
    return 1.45 + (Math.random() * 0.2);
  }
}

export const autoRebalanceService = new AutoRebalanceService();
